version: '3.8'

services:
  cyford-mail:
    build: .
    container_name: cyford-mail
    hostname: mail.cyford.local
    ports:
      - "25:25"     # SMTP
      - "110:110"   # POP3
      - "143:143"   # IMAP
      - "993:993"   # IMAPS
      - "995:995"   # POP3S
      - "8081:80"   # Web interface
    volumes:
      - mail_data:/var/mail
      - mail_logs:/var/log
      - ./:/usr/local/share/cyford/security
    environment:
      - HOSTNAME=mail.cyford.local
      - DOMAIN=cyford.local
      - DOCKER_ENV=true
    privileged: true
    cap_add:
      - NET_ADMIN
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

volumes:
  mail_data:
  mail_logs: